/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.17,
    noseSneerRight: 0.14,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    xDeadEyesLeft: 0.965,
    xDeadEyesRight: 0.689,
    mouthLeft: 0.624,
    eyeLookUpLeft: 0.29,
    eyeLookUpRight: 0.29,
    cheekPuff: 0.9,
    mouthOpen: 0.557,
    mouthSmile: 0.562,
    mouthSmileLeft: 0.639,
    mouthSmileRight: 0.607,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.57,
    noseSneerRight: 0.36,
    eyeSquintLeft: 0.9,
    eyeSquintRight: 0.9,
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    cheekPuff: 0.6,
    mouthOpen: 0.96,
    mouthSmile: 0.96,
    mouthSmileLeft: 0.5,
    mouthSmileRight: 0.5,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

// ─── Voice helpers ────────────────────────────────────────────────────────────

const loadVoices = () =>
  new Promise((resolve) => {
    const voices = speechSynthesis.getVoices();
    if (voices.length > 0) return resolve(voices);
    const handler = () => {
      speechSynthesis.removeEventListener("voiceschanged", handler);
      resolve(speechSynthesis.getVoices());
    };
    speechSynthesis.addEventListener("voiceschanged", handler);
  });

/**
 * Pick the best English voice available.
 * Priority:
 *  1. Google UK English Female  (Chrome desktop)
 *  2. Any en-GB voice
 *  3. Any en-US voice
 *  4. Any voice whose lang starts with "en"
 *  5. null  →  let lang="en-GB" on the utterance do the work
 *
 * We deliberately NEVER fall back to a non-English voice, which was the root
 * cause of "mesagee"-style mispronunciations on Indian browsers where regional
 * voices appear early in the list.
 */
const getEnglishVoice = (voices) => {
  const find = (predicate) => voices.find(predicate) ?? null;

  return (
    find((v) => v.name === "Google UK English Female") ||
    find((v) => v.lang === "en-GB") ||
    find((v) => v.lang === "en-US") ||
    find((v) => v.lang.startsWith("en")) ||
    null
  );
};

// ─── Avatar component ─────────────────────────────────────────────────────────

export function Avatar(props) {
  const group = useRef();

  const { nodes, materials, scene } = useGLTF("/models/68d616575327e5b9d7ee6f07.glb");
  const { animations } = useGLTF("/models/animations.glb");
  const { actions } = useAnimations(animations, group);

  const { message, onMessagePlayed } = useChat();

  const [animation, setAnimation] = useState("Idle");
  const [lipsync, setLipsync] = useState(null);
  const [facialExpression, setFacialExpression] = useState("");
  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);

  const speechStartTime = useRef(0);

  // ── Texture quality ──────────────────────────────────────────────────────
  useEffect(() => {
    scene.traverse((child) => {
      if (!child.isMesh || !child.material) return;
      const mats = Array.isArray(child.material) ? child.material : [child.material];
      mats.forEach((mat) => {
        [mat.map, mat.normalMap].forEach((tex) => {
          if (!tex) return;
          tex.anisotropy = 16;
          tex.minFilter = THREE.LinearFilter;
          tex.magFilter = THREE.LinearFilter;
          tex.needsUpdate = true;
        });
      });
    });
  }, [scene]);

  // ── Animation ────────────────────────────────────────────────────────────
  useEffect(() => {
    if (!actions?.[animation]) return;
    const action = actions[animation];
    action.reset().fadeIn(0.5).play();
    return () => actions[animation]?.fadeOut(0.5);
  }, [animation, actions]);

  // ── Message → speech + lipsync ───────────────────────────────────────────
  useEffect(() => {
    if (!message) {
      setAnimation("Idle");
      setIsSpeaking(false);
      return;
    }

    setAnimation(message.animation || "Idle");
    setFacialExpression(message.facialExpression || "");
    setLipsync(message.lipsync ?? null);
    setIsSpeaking(true);
    speechStartTime.current = Date.now();

    if (!("speechSynthesis" in window)) {
      // Fallback: estimate duration from text length
      const duration = message.text.length * 120;
      const t = setTimeout(() => {
        setIsSpeaking(false);
        onMessagePlayed();
      }, duration);
      return () => clearTimeout(t);
    }

    speechSynthesis.cancel();

    // Small delay so cancel() is processed before the next speak()
    const cancelDelay = setTimeout(() => {
      loadVoices().then((voices) => {
        const utterance = new SpeechSynthesisUtterance(message.text);

        // Always set lang first — this alone prevents regional mispronunciation
        utterance.lang = "en-GB";
        utterance.rate = 0.9;
        utterance.pitch = 1.0;
        utterance.volume = 1.0;

        const voice = getEnglishVoice(voices);
        if (voice) {
          utterance.voice = voice;
          utterance.lang = "en-GB"; // Re-affirm after voice assignment
          console.log("🎤 Speaking with:", voice.name, "|", voice.lang);
        } else {
          console.warn("No English voice found — relying on lang='en-GB'");
        }

        utterance.onstart = () => {
          speechStartTime.current = Date.now();
          setIsSpeaking(true);
        };

        utterance.onend = () => {
          setIsSpeaking(false);
          onMessagePlayed();
        };

        utterance.onerror = (err) => {
          console.error("SpeechSynthesis error:", err);
          setIsSpeaking(false);
          onMessagePlayed();
        };

        // Keep a reference to prevent Chrome GC bug that silently stops events
        window.__currentUtterance = utterance;

        setTimeout(() => speechSynthesis.speak(utterance), 50);
      });
    }, 100);

    return () => clearTimeout(cancelDelay);
  }, [message, onMessagePlayed]);

  // ── Morph helpers ─────────────────────────────────────────────────────────
  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (!child.isSkinnedMesh || !child.morphTargetDictionary) return;
      const idx = child.morphTargetDictionary[target];
      if (idx === undefined) return;
      child.morphTargetInfluences[idx] = THREE.MathUtils.lerp(
        child.morphTargetInfluences[idx],
        value,
        speed
      );
    });
  };

  // ── Per-frame updates ─────────────────────────────────────────────────────
  useFrame(() => {
    // Facial expressions (skip blinks and visemes — handled separately)
    Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).forEach((key) => {
      if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") return;
      if (key.startsWith("viseme_")) return;

      const mapping = facialExpressions[facialExpression];
      lerpMorphTarget(key, mapping?.[key] ?? 0, 0.1);
    });

    // Blink
    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    if (setupMode) return;

    // Lipsync visemes
    const appliedVisemes = [];

    if (message && isSpeaking) {
      if (lipsync?.mouthCues?.length) {
        const elapsed = (Date.now() - speechStartTime.current) / 1000;
        for (const cue of lipsync.mouthCues) {
          if (elapsed >= cue.start && elapsed <= cue.end) {
            const viseme = corresponding[cue.value];
            if (viseme) {
              appliedVisemes.push(viseme);
              lerpMorphTarget(viseme, 1, 0.2);
            }
            break;
          }
        }
      } else {
        // Fallback: cycle visemes rhythmically
        const visemeTargets = ["viseme_AA", "viseme_O", "viseme_U", "viseme_I", "viseme_PP"];
        const active = visemeTargets[Math.floor((Date.now() / 150) % visemeTargets.length)];
        const value = Math.abs(Math.sin(Date.now() * 0.01)) * 0.7 + 0.3;
        appliedVisemes.push(active);
        lerpMorphTarget(active, value, 0.4);
      }
    }

    // Reset inactive visemes
    Object.values(corresponding).forEach((viseme) => {
      if (!appliedVisemes.includes(viseme)) lerpMorphTarget(viseme, 0, 0.1);
    });
  });

  // ── Blink cycle ───────────────────────────────────────────────────────────
  useEffect(() => {
    let timeout;
    const scheduleBlink = () => {
      timeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          scheduleBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    scheduleBlink();
    return () => clearTimeout(timeout);
  }, []);

  // ── Render ────────────────────────────────────────────────────────────────
  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  );
}

useGLTF.preload("/models/68d616575327e5b9d7ee6f07.glb");
useGLTF.preload("/models/animations.glb");